### ISSUE TITLE
Field canno't be search with Sugar Ent 7.8

### ISSUE THREAD

**Issue by fredericrinaldi** [sugarcrmlabs/HighlightDDLBField#1]
Hello Nick,

It's Fred from Switzerland. This new kind of field is really cool and very interesting but there's a missing feature according to my test : we canno't use this field as a search filter (I did my test with a local 7.8 Ent).

Is it the behavior you expected ? or just an enhancement request ?

Kind regards,
Fred

**Comment by cmourizard** [comment]
Hi Fred,

It seems that the filter part is missing, you can take a look on this part of the documentation maybe if you want to do a try to add it: http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.8/User_Interface/Fields/Creating_Custom_Fields/index.html#Enabling_Search_and_Filtering

Cédric

**Comment by nickkrose** [comment]
Hi Fred,

Its something we hadn't added yet. We planned to, but have had other priorities. Feel free to add it. I'm not sure when we'll get time. Would be a while. Cédric is right in his link. Maybe a fun exercise for you? :-)

It would be great to see others contributing to this.

Cheers,
Nick

**Comment by fredericrinaldi** [comment]
Hi Nick and Cédric,

Manny thanks for your quick feedbacks ; I'll ask my tech team to go ahead according Cédric Link and them contribute.

Keep you in touch,

Cheers,
Fred

**Comment by bchevriaut** [comment]
Hello everyone,

I am submitting you the searcheable version of your HighLight field.
I am actually facing an issue. 

When I edit the searchable fields, everything is fine, I can see my HighLight field.
However, if I save it, every other fields in the screen will disappear and it will only show HighLight fields.
Is is like the "filters - operators array" only contains my new field.

This is a layout bug. If I reload the page, everything will be fine and I can find every searchable fields in my listView.

I don't know if I did something wrong or if I am facing a bug.
You can find my version here : 
https://github.com/sugarcrmlabs/HighlightDDLBField/files/833418/HighLightfiled-searchable.zip

Best regards,
Bastien - Dotbase

**Comment by nickkrose** [comment]
Hi Bastien,

This may be a bug in our documentation. We have added your code, with a proper fix. You can see the latest version available now. Thank you for contributing this! This is exactly what I setup this org for, sharing and improving code, with everyone!

Cheers,
Nick
